version: '3'

services:
  db:
    image: postgres
    ports:
      - 65432:5432
    environment:
      POSTGRES_USER: ft_transcendence
      POSTGRES_PASSWORD: "supersecretpassword"
    volumes:
      - ./volume/db:/var/lib/postgresql/data
    restart: always
