version: '3'

networks:
  ft_transcendence:

services:
  http:
    build:
      context: .
      dockerfile: http.Dockerfile
    image: ft_transcendence-http-production
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend
    networks:
      - ft_transcendence
    restart: always
  backend:
    build:
      context: ../..
      dockerfile: docker/main/backend.Dockerfile
    image: ft_transcendence-backend-production
    depends_on:
      - db
      - redis
      - azurite
    volumes:
      - ./volume/redis:/data
    networks:
      - ft_transcendence
    env_file:
      - ../../.env
    restart: always
  frontend:
    build:
      context: ../..
      dockerfile: docker/main/frontend.Dockerfile
    image: ft_transcendence-frontend-production
    networks:
      - ft_transcendence
    env_file:
      - ../../.env
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_USER: ft_transcendence
      POSTGRES_PASSWORD: "supersecretpassword"
    networks:
      - ft_transcendence
    volumes:
      - ./volume/db:/var/lib/postgresql/data
    restart: always
