version: '3'

networks:
  ft_transcendence:

services:
  http:
    build:
      context: .
      dockerfile: http.Dockerfile
    image: ft_transcendence-http
    ports:
      - 443:443
      - 4242:4242
    depends_on:
      - backend
      - frontend
    networks:
      - ft_transcendence
    restart: always
  backend:
    build:
      context: ../..
      dockerfile: docker/main/backend.Dockerfile
    image: ft_transcendence-backend
    depends_on:
      - db
    networks:
      - ft_transcendence
    env_file:
      - ../../.env
    volumes:
      - ./volume/uploads:/usr/src/app/dist/uploads
    restart: always
  frontend:
    build:
      context: ../..
      dockerfile: docker/main/frontend.Dockerfile
    image: ft_transcendence-frontend
    networks:
      - ft_transcendence
    env_file:
      - ../../.env
    restart: always
  db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: ft_transcendence
      POSTGRES_PASSWORD: "supersecretpassword"
    networks:
      - ft_transcendence
    volumes:
      - ./volume/db:/var/lib/postgresql/data
    restart: always
